##theme: jekyll-theme-chirpy
remote_theme: jekyll-theme-Slate

title: "Maria Jose Teran"
description: >-
  Data Science Portfolio â€“ Projects, Resume, and Skills.
show_downloads: true # or false to indicate whether to provide a download URL
# Theme


# Add image
avatar: /assets/img/profile.jpg
favicon: /assets/img/favicons/favicon.ico
