title: "Maria Jose Teran"
description: >-
  Data Science Portfolio â€“ Projects, Resume, and Skills.
show_downloads: true # or false to indicate whether to provide a download URL
# Theme
theme: jekyll-theme-Minimal

# Add image
logo: /assets/img/profile.jpg
favicon: /assets/img/favicon.ico
